import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
import { Providers } from './_components/client/provider/providers'
export const metadata: Metadata = {
  title: 'next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fa">
      <body className={inter.className}>
        <Providers>
          {children}
        </Providers>
        </body>
    </html>
  )
}
